TrajectoryPlannerROS:

  holonomic_robot: false
  
  # Robot Configuration Parameters
  max_vel_x: 0.18
  min_vel_x: 0.08
  max_vel_theta: 1.0 
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 0.6
  
  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.10
  xy_goal_tolerance: 0.05
  
  # Forward Simulation Parameters
  sim_time: 0.8
  meter_scoring: false
  pdistscale: 0.6
  controller_frequency: 10
